.MODEL SMALL
.STACK 100H
.DATA


.CODE
MAIN PROC
	
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,1   ;[FIRST INPUT] 1 IS USED FOR SINGLE CHAR INPUT AND IS STORED IN BH FROM AL (STORED IN AL BY DEFAULT TEMORARYLY)
	INT 21H
	MOV BH,AL
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,1   ;[SECOND INPUT] INPUT ON SINGLE CHAR, STORE IN CH
	INT 21H
	MOV CH,AL
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,1   ;[THIRD INPUT] INPUT ON SINGLE CHAR, STORE IN CH
	INT 21H
	MOV DH,AL
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	
	MOV AH,2   ;SIDE BY SIDE PRINT BH, CH, DH
	MOV DL,BH
	INT 21H
	MOV DL,CH
	INT 21H
	MOV DL,DH
	INT 21H
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	ADD BH,CH  ;BH = BH + CH
	INT 21H
	SUB BH, 30H
	
	ADD BH,DH  ;BH = BH + DH
	INT 21H
	SUB BH, 30H
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,2    ;SHOWING THE ANSWER
	MOV DL,BH
	INT 21H
	
	MAIN ENDP
END MAIN
