.MODEL SMALL
.STACK 100H
.DATA

	A DB "Hello World$"

.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
	
	MOV AH,9  ;STRING OUTPUT
	LEA DX,A  
	INT 21H
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,1   ;1 IS USED FOR SINGLE CHAR INPUT AND IS STORED IN BH FROM AL (STORED IN AL BY DEFAULT TEMORARYLY)
	INT 21H
	MOV BH,AL
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,1   ;INPUT ON SINGLE CHAR, STORE IN CH
	INT 21H
	MOV CH,AL
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	
	MOV AH,2   ;SIDE BY SIDE PRINT BH, CH
	MOV DL,BH
	INT 21H
	MOV DL,CH
	INT 21H
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	ADD BH,CH  ;BH = BH + CH
	INT 21H
	SUB BH, 30H
	
	MOV AH,2   ;FOR PRINT ENDL, 2 IS FOR SINGLE CHAR OUTPUT, 10 IS ENDL, 13 MOVES CURSOR TO FRONT
	MOV DL,10
	INT 21H
	MOV DL,13
	INT 21H
	
	MOV AH,2    ;SHOWING THE ANSWER
	MOV DL,BH
	INT 21H
	
	MAIN ENDP
END MAIN
